import { Container, Flex, Panel } from 'roku-ui'
import Head from 'next/head'
import Link from 'next/link'
export default function Home () {
  return (
    <>
      <Head>
        <title>GPT Prompt Mate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div style={{
            fontSize: '2rem',
            fontWeight: 'bold',
            textAlign: 'center',
            padding: '1rem',
            background: 'linear-gradient(to right, #4b86b4, #8d4bbb)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
          }}>GPT Prompt Mate</div>
          <Flex gap="0.5rem">
            <Link href="/scenes/06">
              <Panel padding border>
                <div style={{
                  fontSize: '1.5rem',
                  fontWeight: 'bold',
                }}>
                06 Girl
                </div>
                <div>
                AI.
                </div>
              </Panel>
            </Link>
          </Flex>
        </Container>
      </main>
    </>
  )
}
